version: 2

jobs:
  build:
    docker:
      - image: circleci/android:api-28

    steps:
        - checkout
        - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

        - run:
            name: Resolve dependencies
            command: ./gradlew app:dependencies

        - save_cache:
            paths:
              - ~/.gradle
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

        - run:
            name: Assemble (Hathor)
            command: ./gradlew clean assembleHathorRelease -PdisablePreDex

        - run:
            name: Assemble (FOSS)
            command: ./gradlew assembleFossRelease -PdisablePreDex -PdisableCrashlytics

        - run:
            name: Test Hathor Release
            command: ./gradlew testHathorRelease -PdisablePreDex
